/**
 * Default categories seeded for every new user (PRD F10.1).
 *
 * `keywords` drives deterministic category inference (PRD F10.4) — a keyword
 * map, never an LLM call. GUARDRAILS.md section 1: no paid inference APIs.
 *
 * Colour tokens map to the palette in DESIGN.md section 2.3. Categories store a
 * token name, never a hex value, so the palette can be retuned centrally.
 */

export type CategoryKind = 'expense' | 'income';

export interface CategorySeed {
  slug: string;
  name: string;
  emoji: string;
  colorToken: string;
  kind: CategoryKind;
  keywords: readonly string[];
  /** Excluded from the safe-to-spend calculation (PRD F6.7). */
  excludeFromBudget: boolean;
  sortOrder: number;
}

export const DEFAULT_CATEGORIES: readonly CategorySeed[] = [
  {
    slug: 'food',
    name: 'Food',
    emoji: '🍜',
    colorToken: 'food',
    kind: 'expense',
    keywords: [
      'food',
      'lunch',
      'dinner',
      'breakfast',
      'brunch',
      'supper',
      'kopi',
      'coffee',
      'cafe',
      'restaurant',
      'hawker',
      'kopitiam',
      'mcd',
      'macdonald',
      'mcdonalds',
      'kfc',
      'starbucks',
      'bubble tea',
      'boba',
      'snack',
      'takeaway',
      'foodpanda',
      'deliveroo',
    ],
    excludeFromBudget: false,
    sortOrder: 10,
  },
  {
    slug: 'groceries',
    name: 'Groceries',
    emoji: '🛒',
    colorToken: 'groceries',
    kind: 'expense',
    keywords: [
      'grocery',
      'groceries',
      'supermarket',
      'ntuc',
      'fairprice',
      'cold storage',
      'sheng siong',
      'giant',
      'market',
      'wet market',
      'redmart',
    ],
    excludeFromBudget: false,
    sortOrder: 20,
  },
  {
    slug: 'transport',
    name: 'Transport',
    emoji: '🚇',
    colorToken: 'transport',
    kind: 'expense',
    keywords: [
      'transport',
      'mrt',
      'bus',
      'train',
      'ez-link',
      'ezlink',
      'grab',
      'gojek',
      'taxi',
      'cab',
      'comfort',
      'petrol',
      'fuel',
      'parking',
      'erp',
      'flight',
      'simplygo',
    ],
    excludeFromBudget: false,
    sortOrder: 30,
  },
  {
    slug: 'shopping',
    name: 'Shopping',
    emoji: '🛍️',
    colorToken: 'shopping',
    kind: 'expense',
    keywords: [
      'shopping',
      'clothes',
      'shoes',
      'uniqlo',
      'zara',
      'shopee',
      'lazada',
      'taobao',
      'amazon',
      'electronics',
      'gadget',
    ],
    excludeFromBudget: false,
    sortOrder: 40,
  },
  {
    slug: 'bills',
    name: 'Bills',
    emoji: '🧾',
    colorToken: 'bills',
    kind: 'expense',
    keywords: [
      'bill',
      'bills',
      'rent',
      'utilities',
      'electricity',
      'water',
      'gas',
      'wifi',
      'internet',
      'phone',
      'mobile',
      'singtel',
      'starhub',
      'm1',
      'sp group',
      'insurance',
      'subscription',
      'netflix',
      'spotify',
      'icloud',
    ],
    excludeFromBudget: false,
    sortOrder: 50,
  },
  {
    slug: 'health',
    name: 'Health',
    emoji: '💊',
    colorToken: 'health',
    kind: 'expense',
    keywords: [
      'health',
      'doctor',
      'clinic',
      'hospital',
      'pharmacy',
      'guardian',
      'watsons',
      'dentist',
      'medicine',
      'gym',
      'fitness',
      'supplement',
    ],
    excludeFromBudget: false,
    sortOrder: 60,
  },
  {
    slug: 'entertainment',
    name: 'Entertainment',
    emoji: '🎬',
    colorToken: 'entertainment',
    kind: 'expense',
    keywords: [
      'entertainment',
      'movie',
      'cinema',
      'golden village',
      'gv',
      'concert',
      'game',
      'steam',
      'playstation',
      'bar',
      'drinks',
      'karaoke',
      'ktv',
    ],
    excludeFromBudget: false,
    sortOrder: 70,
  },
  {
    slug: 'travel',
    name: 'Travel',
    emoji: '✈️',
    colorToken: 'travel',
    kind: 'expense',
    keywords: [
      'travel',
      'hotel',
      'airbnb',
      'booking',
      'agoda',
      'airasia',
      'scoot',
      'singapore airlines',
      'luggage',
      'visa fee',
      'tour',
    ],
    excludeFromBudget: false,
    sortOrder: 80,
  },
  {
    slug: 'education',
    name: 'Education',
    emoji: '📚',
    colorToken: 'education',
    kind: 'expense',
    keywords: [
      'education',
      'course',
      'tuition',
      'book',
      'books',
      'udemy',
      'coursera',
      'school fee',
      'exam',
    ],
    excludeFromBudget: false,
    sortOrder: 90,
  },
  {
    slug: 'gifts',
    name: 'Gifts',
    emoji: '🎁',
    colorToken: 'gifts',
    kind: 'expense',
    keywords: ['gift', 'gifts', 'present', 'angpao', 'ang bao', 'donation', 'birthday', 'wedding'],
    excludeFromBudget: false,
    sortOrder: 100,
  },
  {
    slug: 'transfers',
    name: 'Transfers',
    emoji: '🔁',
    colorToken: 'transfers',
    kind: 'expense',
    // PRD Q3: excluded from budget by default — moving your own money between
    // accounts is not spending, and counting it would distort safe-to-spend.
    keywords: [
      'transfer',
      'paynow',
      'paylah',
      'topup',
      'top up',
      'savings',
      'invest',
      'cpf',
      'repayment',
    ],
    excludeFromBudget: true,
    sortOrder: 110,
  },
  {
    slug: 'uncategorised',
    name: 'Uncategorised',
    emoji: '❓',
    colorToken: 'uncategorised',
    kind: 'expense',
    keywords: [],
    excludeFromBudget: false,
    sortOrder: 999,
  },

  // --- income ---------------------------------------------------------------
  {
    slug: 'salary',
    name: 'Salary',
    emoji: '💰',
    colorToken: 'groceries',
    kind: 'income',
    keywords: ['salary', 'pay', 'payday', 'wage', 'payroll'],
    excludeFromBudget: false,
    sortOrder: 200,
  },
  {
    slug: 'bonus',
    name: 'Bonus',
    emoji: '🎉',
    colorToken: 'entertainment',
    kind: 'income',
    keywords: ['bonus', 'commission', 'incentive', 'ang bao received'],
    excludeFromBudget: false,
    sortOrder: 210,
  },
  {
    slug: 'refund',
    name: 'Refund',
    emoji: '↩️',
    colorToken: 'transport',
    kind: 'income',
    keywords: ['refund', 'reimbursement', 'reimburse', 'rebate', 'cashback', 'claim'],
    excludeFromBudget: false,
    sortOrder: 220,
  },
  {
    slug: 'investment',
    name: 'Investment',
    emoji: '📈',
    colorToken: 'travel',
    kind: 'income',
    keywords: ['dividend', 'interest', 'investment', 'payout', 'capital gain'],
    excludeFromBudget: false,
    sortOrder: 230,
  },
  {
    slug: 'other-income',
    name: 'Other Income',
    emoji: '✨',
    colorToken: 'gifts',
    kind: 'income',
    keywords: [],
    excludeFromBudget: false,
    sortOrder: 240,
  },
];

export const UNCATEGORISED_SLUG = 'uncategorised';
export const OTHER_INCOME_SLUG = 'other-income';

/** Words that make a bare amount read as income even without a leading `+`. */
export const INCOME_KEYWORDS: readonly string[] = [
  'salary',
  'bonus',
  'refund',
  'reimbursement',
  'reimburse',
  'dividend',
  'payout',
  'cashback',
  'rebate',
  'received',
  'income',
];
